import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/providers/TQProvider';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'LOLpedia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <Providers>
          <Header />
          <div className="w-screen mt-[70px] max-h-screen min-h-[cal(100vh-70px)]">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
