import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/providers/TQProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'LOLpedia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system">
            <Header />
            <div className="pt-[60px] md:pt-[70px]">{children}</div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
